### ISSUE TITLE
unsupported ext tag detected: EXT-X-INDEPENDENT-SEGMENTS

### ISSUE THREAD

**Issue by kalemeister** [iheartradio/open-m3u8#56]
Hi.
I've run across a new issue. Maybe just evolution of m3u8 playlists, but a new tag that's not supported.

com.iheartradio.m3u8.ParseException: unsupported ext tag detected: EXT-X-INDEPENDENT-SEGMENTS - #EXT-X-INDEPENDENT-SEGMENTS
	at com.iheartradio.m3u8.ParseException.create(ParseException.java:35)
	at com.iheartradio.m3u8.ExtendedM3uParser.parse(ExtendedM3uParser.java:66)
	at com.iheartradio.m3u8.PlaylistParser.parse(PlaylistParser.java:115)

You can get the playlist that has these tags here.
https://ngcstatpack-a.akamaihd.net/Nat_Geo_Channels/896/599/1509829223445/Long_Road_101_HD_Clean_AUTH_movie.m3u8

I will probably work on integrating this is my clone so if you don't have anything by the time I do I'll post my edits for you.

**Comment by psk-ixolit** [comment]
Adding `ParsingMode.LENIENT` bypasses this error:

`Playlist playlist = new PlaylistParser(someinputstream, Format.EXT_M3U, Encoding.UTF_8, ParsingMode.LENIENT).parse();`
